[package]
name = "codecrafters-shell"
version = "0.1.0"
authors = ["Codecrafters <hello@codecrafters.io>"]
edition = "2024"
rust-version = "1.91"

[dependencies]
rustyline = "17.0.1"
anyhow = "1.0"
indexmap = "2.0"
duct = "1.1.1"

[dev-dependencies]
pretty_assertions = "1.4.1"
rstest = "0.26.1"
